name: release

on:
  push:
    branches: [main, master]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get Go version
        id: vars
        run: |
          goVersion=$(grep '^FROM go' .github/go/Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
          echo "go_version=${goVersion}" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ steps.vars.outputs.go_version }}

      - name: Semantic Release
        id: semver
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-generator-opt: "emojis=true"
          allow-initial-development-versions: true

      - name: Set up GoReleaser
        if: steps.semver.outputs.version != ''
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --config .github/.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: v${{ steps.semver.outputs.version }}
